version: '3.3'
services:
  chatgpt:
    container_name: chatgpt
    image: breathbath/chatgpt
    depends_on:
      - redis
    restart: always
    entrypoint: /app/chatgpt telegram
    volumes:
      - ./.env.local:/app/.env.local
      - ./.env.secret:/app/.env.secret
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ./DockerData/redis:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    entrypoint: redis-server --appendonly yes