version: '3.3'
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wine
    volumes:
      - ./mysql/migration:/docker-entrypoint-initdb.d
      - mysql8-data:/var/lib/mysql:rw
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3309:3306
  chatgpt:
    container_name: chatgpt
    image: breathbath/chatgpt:${APP_VERSION}
    depends_on:
      - redis
    restart: always
    entrypoint: /app/chatgpt telegram
    volumes:
      - ./.env.local:/app/.env.local
      - ./.env.secret:/app/.env.secret
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ./DockerData/redis:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    entrypoint: redis-server --appendonly yes
    restart: always
volumes:
  mysql8-data:
