{
 "title": "Usage Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Unique Users",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "wine",
     "rawSql": "SELECT\n  COUNT(DISTINCT user_id) AS \"count\",\n  $__timeGroup(session_start,'5m', 0) as time\nFROM\n  wine.usage_stats\nWHERE\n  $__timeFilter(session_start)\nGROUP BY\n  time"
    }
   ]
  },
  {
   "title": "Total requests count",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "wine",
     "rawSql": "SELECT\n  COUNT(*) AS \"count\",\n  $__timeGroup(session_start,'5m', 0) as time\nFROM\n  wine.usage_stats\nWHERE\n  $__timeFilter(session_start)\nGROUP BY\n  time\nLIMIT\n  50"
    }
   ]
  },
  {
   "title": "Raw Data",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "dataset": "wine",
     "rawSql": "SELECT\n  user_id 'user id',\n  (input_prompt_tokens + input_completion_tokens + gen_completion_tokens + gen_prompt_tokens) 'toal tokens',\n  is_voice_input 'is voice',\n  input 'prompt', TIMESTAMPDIFF(SECOND, session_start, session_end) AS 'duration seconds',\n  input_prompt_tokens 'prompt tokens',\n  input_completion_tokens 'compl tokens',\n  gen_completion_tokens 'reco completion tokens',\n  gen_prompt_tokens 'reco prompt tokens',\n    session_start as 'started',\n    session_end as 'end',\n  gpt_model 'model'\nFROM\n  wine.usage_stats\nWHERE \n  $__timeFilter(session_start)\nORDER BY session_start DESC\nLIMIT\n  50"
    }
   ]
  },
  {
   "title": "Recommendation Tracking",
   "type": "logs",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "wine",
     "rawSql": "SELECT\n  *\nFROM\n  wine.recommendations\nWHERE \n  $__timeFilter(created_at)\nLIMIT\n  50"
    }
   ]
  }
 ]
}